// Import Vitest's config helper.
// This gives us type-safe configuration for the test runner.
import { defineConfig } from 'vitest/config';

// Import the tsconfig paths plugin.
// This lets Vitest understand path aliases generated by NestJS libraries.
import tsconfigPaths from 'vite-tsconfig-paths';

// Export the Vitest configuration.
// Vitest will automatically load this file when we run `npm run test`.
export default defineConfig({
  // Enable TypeScript path aliases from tsconfig.json.
  plugins: [tsconfigPaths()],

  test: {
    // Enable global test functions like describe, it, and expect.
    // This keeps our tests clean and familiar.
    globals: true,

    // Use the Node.js test environment because this is a backend project.
    environment: 'node',

    // Look for test files inside all NestJS apps and libraries.
    include: ['apps/**/*.spec.ts', 'libs/**/*.spec.ts'],

    // Exclude compiled output and dependencies from test discovery.
    exclude: ['node_modules', 'dist'],

    coverage: {
      // Use the V8 coverage provider.
      // This works well for modern Node.js projects.
      provider: 'v8',

      // Store coverage reports in the coverage folder.
      reportsDirectory: 'coverage',
    },
  },
});
