/**
 * Event emitted when Account Service creates an account.
 */
export interface AccountCreatedEvent {
  /**
   * Unique account ID generated by Account Service.
   */
  accountId: string;

  /**
   * User who owns the account.
   */
  userId: string;

  /**
   * Type of account created.
   */
  accountType: 'SAVINGS' | 'CHECKING' | 'WALLET';

  /**
   * Current account status.
   */
  status: 'PENDING' | 'ACTIVE' | 'FROZEN' | 'CLOSED';

  /**
   * Account currency.
   */
  currency: 'PHP' | 'USD';

  /**
   * Unique event ID used by consumers for idempotency checks.
   */
  eventId: string;

  /**
   * Shared workflow ID used to trace logs across services.
   */
  correlationId: string;

  /**
   * ISO timestamp when the event was created.
   */
  createdAt: string;
}
