/**
 * Event emitted when a user requests a bill payment.
 * Ledger Service listens to this event and posts debit/credit entries.
 */
export interface BillPaymentRequestedEvent {
  /**
   * Unique bill payment ID generated by Bill Payment Service.
   */
  billPaymentId: string;

  /**
   * User who requested the bill payment.
   */
  userId: string;

  /**
   * User account where money will be deducted.
   */
  fromAccountId: string;

  /**
   * Biller receiving the payment.
   */
  billerId: string;

  /**
   * Customer account/reference number at the biller.
   */
  billerReferenceNumber: string;

  /**
   * Amount in minor units.
   */
  amountMinor: number;

  /**
   * Currency code.
   */
  currency: 'PHP' | 'USD';

  /**
   * User-provided idempotency key to prevent duplicate bill payments.
   */
  idempotencyKey: string;

  /**
   * Unique event ID used by consumers for idempotency checks.
   */
  eventId: string;

  /**
   * Shared workflow ID used to trace logs across services.
   */
  correlationId: string;

  /**
   * ISO timestamp when request was created.
   */
  createdAt: string;
}
