/**
 * Event emitted when File Service successfully stores a file.
 */
export interface FileUploadedEvent {
  /**
   * Unique file metadata ID generated by File Service.
   */
  fileId: string;

  /**
   * User who owns the uploaded file.
   */
  userId: string;

  /**
   * Business purpose of the file.
   */
  purpose: 'KYC_DOCUMENT' | 'SUPPORT_DOCUMENT' | 'STATEMENT';

  /**
   * KYC document type if the file is for KYC.
   */
  documentType?: 'GOVERNMENT_ID' | 'PROOF_OF_ADDRESS' | 'SELFIE';

  /**
   * S3-style bucket where the file is stored.
   */
  bucket: string;

  /**
   * Object key inside the bucket.
   */
  objectKey: string;

  /**
   * Original filename from the upload.
   */
  originalName: string;

  /**
   * File MIME type.
   */
  mimeType: string;

  /**
   * File size in bytes.
   */
  sizeBytes: number;

  /**
   * Unique event ID used by consumers for idempotency checks.
   */
  eventId: string;

  /**
   * Shared workflow ID used to trace logs across services.
   */
  correlationId: string;

  /**
   * ISO timestamp when this event was created.
   */
  createdAt: string;
}
