/**
 * Event emitted when a user requests a money transfer.
 * Ledger Service listens to this event and posts debit/credit entries.
 */
export interface TransferRequestedEvent {
  /**
   * Unique transfer ID generated by Transfer Service.
   */
  transferId: string;

  /**
   * User who initiated the transfer.
   */
  userId: string;

  /**
   * Account where money will be deducted.
   */
  fromAccountId: string;

  /**
   * Account where money will be credited.
   */
  toAccountId: string;

  /**
   * Transfer amount in minor currency units.
   */
  amountMinor: number;

  /**
   * Currency code for the transfer.
   */
  currency: 'PHP' | 'USD';

  /**
   * User-provided idempotency key to prevent duplicate transfers.
   */
  idempotencyKey: string;

  /**
   * Unique event ID used by consumers for idempotency checks.
   */
  eventId: string;

  /**
   * Shared workflow ID used to trace logs across services.
   */
  correlationId: string;

  /**
   * ISO timestamp when this event was created.
   */
  createdAt: string;
}
