/**
 * Event emitted when a user registers successfully.
 * User Profile Service consumes this event to create a profile.
 */
export interface UserRegisteredEvent {
  /**
   * Unique user ID generated by Auth Service.
   */
  userId: string;

  /**
   * User email address.
   */
  email: string;

  /**
   * User display name.
   */
  fullName: string;

  /**
   * Role assigned during registration.
   */
  role: 'USER' | 'SUPPORT' | 'COMPLIANCE_OFFICER' | 'ADMIN';

  /**
   * Unique event ID used by consumers for idempotency checks.
   */
  eventId: string;

  /**
   * Shared workflow ID used to trace logs across services.
   */
  correlationId: string;

  /**
   * ISO timestamp when the event was created.
   */
  createdAt: string;
}
